class CreateSecondaries < ActiveRecord::Migration
  def change
    create_table :secondaries do |t|
      t.integer :workorganization
      t.string :cmt1
      t.integer :followupsystem
      t.string :cmt2
      t.integer :measuringprogram
      t.string :cmt3
      t.integer :quailtyculture
      t.string :cmt4
      t.integer :messegesystem
      t.string :cmt5
      t.integer :studentshonoring
      t.string :cmt6
      t.integer :teachershonoring
      t.string :cmt7
      t.integer :schoolboard
      t.string :cmt8
      t.integer :selfevaluation
      t.string :cmt9
      t.integer :schoolapplying
      t.string :cmt10
      t.integer :oneteamspirit
      t.string :cmt11
      t.integer :otherschooltwin
      t.string :cmt12
      t.integer :requiredworkcompletion
      t.string :cmt13
      t.integer :noorprogramcompletion
      t.string :cmt14
      t.integer :takamolcompletion
      t.string :cmt15
      t.integer :schoolweb
      t.string :cmt16
      t.integer :classenvironment
      t.string :cmt17
      t.integer :schoolfacilities
      t.string :cmt18
      t.integer :schoolcafeteria
      t.string :cmt19
      t.integer :healthpromoting
      t.string :cmt20
      t.integer :walltexting
      t.string :cmt21
      t.integer :schoolactivities
      t.string :cmt22
      t.integer :islamicawareness
      t.string :cmt23
      t.integer :proceduralplan
      t.string :cmt24
      t.integer :proceduralsystemic
      t.string :cmt25
      t.integer :proceduralsystemic2
      t.string :cmt26
      t.integer :teacherinout
      t.string :cmt27
      t.integer :waitingclasses
      t.string :cmt28
      t.integer :morningsupervision
      t.string :cmt29
      t.integer :schooltable
      t.string :cmt30
      t.integer :attendancepercentage
      t.string :cmt31
      t.integer :writtenpreparation
      t.string :cmt32
      t.integer :ratingrecords
      t.string :cmt33
      t.integer :activitiesbook
      t.string :cmt34
      t.integer :editorialbusiness
      t.string :cmt35
      t.integer :visitingteachers
      t.string :cmt36
      t.integer :teachingaidsusage
      t.string :cmt37
      t.integer :commissionguidance
      t.string :cmt38
      t.integer :enrichmentprogram
      t.string :cmt39
      t.integer :schoolplan
      t.string :cmt40
      t.integer :trainingprograms
      t.string :cmt41
      t.integer :techemploying
      t.string :cmt42
      t.integer :richmentprogramdev
      t.string :cmt43
      t.integer :teachingnewstrategy
      t.string :cmt44
      t.integer :learningresource
      t.string :cmt45
      t.integer :headmasterpermission
      t.string :cmt46
      t.integer :creativeapproaches
      t.string :cmt47
      t.integer :schoolinitiative
      t.string :cmt48
      t.integer :achievementfile
      t.string :cmt49
      t.integer :examssystems
      t.string :cmt50
      t.integer :qeiyasschoollevel
      t.string :cmt51
      t.string :cmt52
      t.integer :studentsinawards
      t.integer :studentsoutawards
      t.string :cmt53
      t.integer :safetycoordinator
      t.string :cmt54
      t.integer :teachertraining
      t.string :cmt55
      t.integer :buildingsafety
      t.string :cmt56
      t.integer :evacuationexperment
      t.string :cmt57
      t.integer :fireextinguishers
      t.string :cmt58
      t.integer :emergencyexit
      t.string :cmt59
      t.integer :alarm
      t.string :cmt60
      t.integer :safetymethods
      t.string :cmt61
      t.integer :sum

      t.timestamps
    end
  end
end
